spring:
  application:
    name: Api-Gateway


#api gateway config
  cloud:
    gateway:
      routes:
        - id: Order-Service #application name
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/** , /api/v1/orders/<future endpoints>
            - Method= GET, POST, PUT, DELETE
          filters:
            - StripPrefix=2
            - RedirectTo=302, http://codingshuttle.com #it will redirect u to this link


        - id: Inventory-Service #application name
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/** , /inventory/<future endpoints>
            - Method= GET, POST, PUT, DELETE
          filters:
              - StripPrefix=2
              - AddRequestHeader=X-Custom-Header, Anuj

#eureka client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 1000